
//PRODUCTS
export const FETCH_PRODUCT_LIST = "FETCH_PRODUCT_LIST";
export const FETCH_PRODUCT_DETAIL = "FETCH_PRODUCT_DETAIL";
export const FETCH_SEARCHED_PRODUCT = "FETCH_SEARCHED_PRODUCT";

//PREVIOUS ORDER
export const FETCH_PREVIOUS_ORDER = "FETCH_PREVIOUS_ORDER";
export const FETCH_PREV_ORDER_STORAGE = "FETCH_PREV_ORDER_STORAGE";

//CATEGORIES
export const FETCH_CATEGORY_LIST = "FETCH_CATEGORY_LIST";

//AUTH
export const FETCH_SIGN_IN_PERMISSION = "FETCH_SIGN_IN_PERMISSION";

//BASKET
export const FETCH_ADD_BASKET = "FETCH_ADD_BASKET";
export const GET_BASKET_STORAGE = "GET_BASKET_STORAGE";
export const FETCH_BASKET_ACTION_COUNT_ITEM = "FETCH_BASKET_ACTION_COUNT_ITEM";

